[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ironBars"
version = "0.2.1"
description = "A lightweight Python utility library providing handy functions for efficient data handling, CSV management, and Google Sheets integration."
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "Sevrus", email = "b25bs1304@iitj.ac.in" }
]
license = { text = "LICENSE" }
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]

dependencies = [
  "pandas>=2.3.2",
  "numpy>=2.3.3",
  "requests>=2.32.5"
]

[project.urls]
homepage = "https://github.com/sevruscorporations/ironbars"
repository = "https://github.com/sevruscorporations/ironbars"
