[project]
name = "moduvent"
version = "4.1"
authors = [
    { name = "Joxos", email = "xujunhao61@163.com" }
]
description = "A lightweight, modular event system for Python applications with plugin architecture support."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
]
