[project]
name = "undockit"
description = "run dockerfiles as commands"
version = "0.0.3"
authors = [
    { name = "Gareth Davidson", email = "gaz@bitplane.net" }
]
readme = "README.md"
license = {text = "Public Domain"}
requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/bitplane/undockit"
Repository = "https://github.com/bitplane/undockit"
"Bug Tracker" = "https://github.com/bitplane/undockit/issues"

[project.scripts]
undockit = "undockit.main:main"

[project.optional-dependencies]
dev = [
    "pre-commit",
    "pytest",
    "coverage",
    "pytest-cov",
    "build",
    "twine",
    "ruff",
    "pydoc-markdown"
]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.format]
docstring-code-format = true
