[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tq42-grpc-client"
version = "1.0.271"
description = "gRPC client to call TQ42 endpoints"
readme = "README.md"
authors = [{ name = "TQ42" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["tq42", "gRPC", "client"]
dependencies = [
    "protobuf >= 5.28.2",
    "grpcio-tools >= 1.54.0",
    "protovalidate == 0.5.0",
    
    "six == 1.17.0",
    "python-dateutil == 2.9.0.post0",
    "tzdata == 2025.2",
    "lark == 0.12.0",
    "pendulum == 3.1.0",
    "pyyaml == 6.0.2",
    "types-pyyaml == 6.0.12.20250516",
    "cel-python == 0.3.0",
    "grpcio == 1.73.0",
    "protobuf == 6.31.1",
    "typing-extensions == 4.14.0",
    "exceptiongroup == 1.3.0",
    "grpcio-tools == 1.73.0",
    "iniconfig == 2.1.0",
    "packaging == 25.0",
    "pluggy == 1.6.0",
    "tomli == 2.2.1",
    "pytest == 7.4.4",
]
requires-python = ">=3.8"

[project.optional-dependencies]
dev = []

[tool.setuptools.package-data]
"*" = ["*.pyi"]

[project.urls]
Homepage = "https://terraquantum.swiss/"
