[project]
name = "init-mater-project"
version = "0.1.4"
description = "A MATER project generator"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    { name = "Lauranne Sarribouette", email = "lauranne.sarribouette@univ-grenoble-alpes.fr" },
    { name = "francois-verzier", email = "francois.verzier@univ-grenoble-alpes.fr" }
]
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console", 
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13", 
    "Topic :: Software Development :: Code Generators",
    "Topic :: Scientific/Engineering",
]
keywords = [
    "mater", "project-generator", "cli", "template", 
    "simulation", "code-generator", "scientific", "research"
]
dependencies = [
    "click>=8.2.1",
    "email-validator>=2.2.0",
    "jinja2>=3.1.6",
    "mater>=0.12.3",
    "pandas>=2.2.3",
    "pydantic>=2.11.9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipython>=9.2.0",
    "ruff>=0.11.11",
]
test = [
    "pytest-cov>=6.1.1",
    "pytest>=8.3.5",
    "pytest-mock>=3.14.0",
]
docs = [
    "pydata-sphinx-theme>=0.16.1",
    "sphinx-copybutton>=0.5.2",
    "sphinx>=8.2.3",
    "sphinx-design>=0.6.1",
    "setuptools>=80.9.0",
    "myst-parser>=4.0.1",
]

[project.urls]
"Repository" = "https://gricad-gitlab.univ-grenoble-alpes.fr/isterre-dynamic-modeling/mater-project/init-mater-project"
"Documentation" = "https://isterre-dynamic-modeling.gricad-pages.univ-grenoble-alpes.fr/mater-project/init-mater-project"

[project.scripts]
init-mater-project = "init_mater_project.main:main"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff.lint.per-file-ignores]
# Pytest auto-discovers fixtures in conftest.py, appearing unused to static analysis
"**/conftest.py" = ["F401"] 