[build-system]
build-backend = "hatchling.build"

requires = ["hatchling"]

[tool.hatch.build]
only-include = ["src"]
[tool.hatch.build.targets.dist]
packages = ["src/ddpc"]
[tool.hatch.build.targets.wheel]
packages = ["src/ddpc"]

[project]
name = "ddpc"
version = "2025.9.26"
description = "DFT Data Processing Core"
readme = "README.md"
authors = [{ name = "zzl", email = "ZhengZhilin@hzwtech.com" }]
requires-python = ">=3.12,<4.0"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
dependencies = [
  "ase>=3.25",           # io, basic structure
  "h5py>=3.14",          # read hdf5 file
  "loguru>=0.7.3",       # logging
  "polars>=1.31",        # data export
  "pymatgen>=2025.6.14", # find orth
  "spglib>=2.6",         # symmetry, find primitive cell
]
license = 'MIT'

[dependency-groups]
dev = [
  "hatch>=1.14.1",               # build package
  "mypy>=1.16.1",                # typing
  "pytest>=8.4.1",               # test framework
  "pytest-xdist>=3.8",           # parallel test
  "ruff>=0.12.2",                # format and check syntax
  "sphinx-immaterial>=0.13.5",   # doc theme
  "syrupy>=4.9.1",               # pytest snapshot
  "twine>=6.1.0",                # upload package to pypi
  "sphinxcontrib-napoleon>=0.7", # numpy doc style
]
