# Other project metadata fields as specified in:
# https://packaging.python.org/en/latest/specifications/declaring-project-metadata/
# https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "core-https"
description = "This project/library contains common elements related to HTTP & API services..."
version = "2.0.0"

authors = [
    {name = "Alejandro Cora González", email = "alek.cora.glez@gmail.com"}
]

maintainers = [
    {name = "Alejandro Cora González"}
]

requires-python = ">=3.9"
license = {text = "MIT"}
readme = "README.rst"

classifiers = [
    # Classifiers -> https://pypi.org/classifiers/
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Development Status :: 5 - Production/Stable",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

dependencies = [
    "aiohttp>=3.12.0,<4.0.0; python_version >= '3.9'",
    "core-mixins>=2.1.0",
    "core-tests>=2.0.1",
    "requests>=2.32.3,<3.0.0; python_version >= '3.9'",
    "typing-extensions>=4.8.0; python_version >= '3.9' and python_version < '3.11'",
    "urllib3>=2.2.3,<3.0.0; python_version >= '3.9'",
]

[project.optional-dependencies]
dev = [
    "core-dev-tools>=1.0.1",
    "types-requests>=2.32.0.20250602",
]

[project.urls]
Homepage = "https://gitlab.com/bytecode-solutions/core/core-https"
Repository = "https://gitlab.com/bytecode-solutions/core/core-https"
Documentation = "https://core-https.readthedocs.io/en/latest/"
Issues = "https://gitlab.com/bytecode-solutions/core/core-https/-/issues"
Changelog = "https://gitlab.com/bytecode-solutions/core/core-https/-/blob/master/CHANGELOG.md"

[tool.setuptools.package-data]
"core_https" = ["py.typed"]
