[project]
name = "quantification"
version = "0.1.3"
description = ""
authors = [
    {name = "realhuhu",email = "2661467107@qq.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "pydantic (>=2.11.7,<3.0.0)",
    "akshare (>=1.17.22,<2.0.0)",
    "pydantic-settings (>=2.10.1,<3.0.0)",
    "tushare (>=1.4.21,<2.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "pycryptodome (>=3.23.0,<4.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
