[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
[project]
name = "swiss-weatherdata"
version = "0.0.1"
authors = [
  { name="Michel Matter", email="mich1983mat@gmail.com" },
]
description = "An API to easily download open access weather recordings from MeteoSwiss"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "pandas>=2.2.3"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/ptitmatheux/swiss_weather"
Issues = "https://github.com/ptitmatheux/swiss_weather/issues"
