[project]
name = "calsipro"
version ="1.0.1"
authors = [{name = "Simon Haendeler", email="opensource@haend.de"}]
description = "Calcium Signal Propagation Speed Analysis Library"
dependencies = [
    "bioio>=3.0.0",
    "bioio-czi>=2.4.0",
    "bioio-imageio>=1.3.0",
    "bokeh>=3.1.1",
    "click>=8.1.8",
    "datashader>=0.15.2",
    "ffmpeg-python>=0.2.0",
    "matplotlib>=3.10.6",
    "numba>=0.58.1",
    "numpy>=1.24.4",
    "openpyxl>=3.1.5",
    "pillow>=10.4.0",
    "polars>=1.8.2",
    "pywavelets>=1.4.1",
    "scikit-image>=0.25.2",
    "scikit-learn>=1.7.2",
    "scipy>=1.10.1",
]
requires-python = ">=3.10,<3.12"

[project.scripts]
calsipro = "calsipro.cli:cli"

[tool.ruff]
line-length = 120

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
