[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"


[project]

name = "imRender"
dynamic = ["version"]
description = "."
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "loguru>=0.7.2", "tqdm", "pillow", "opencv-python"
]


[tool.setuptools.dynamic]
version = { attr = "imRender.__version__" }

[tool.setuptools.packages.find]
where = ["."]
include = ["imRender/*"]

[project.scripts]
# 命令 = "包名.模块:函数"

[project.urls]
"Github" = "https://github.com/firstelfin/imRender"
