[project]
name = "yta-numpy-resizer"
version = "0.0.1"
description = "Youtube Autonomous Numpy Resizer Module"
authors = [
    {name = "danialcala94",email = "danielalcalavalera@gmail.com"}
]
readme = "README.md"
requires-python = "==3.9"
dependencies = [
    # This is needed to obtain some results
    "opencv-python (>=0.0.1,<99.0.0)",
    "numpy (>=0.0.1,<99.0.0)"
]

[tool.poetry]
packages = [{include = "yta_numpy_resizer", from = "src"}]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
