[build-system]
requires = ["ase", "defusedxml", "matplotlib", "numpy", "pandas", "scipy", "hatchling==1.27.0", "hatch-vcs==0.5.0"]
build-backend = "hatchling.build"

[project]
name = "pyiron_vasp"
description = "Parser for the Vienna Ab initio Simulation Package (VASP)"
authors = [
    { name = "Jan Janssen", email = "janssen@mpie.de" },
]
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["pyiron"]
requires-python = ">=3.9, <3.14"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Scientific/Engineering :: Physics",
    "License :: OSI Approved :: BSD License",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "ase>=3.23.0,<=3.26.0",
    "defusedxml>=0.7.0,<=0.7.1",
    "numpy>=1.26.0,<=2.3.3",
    "pandas>=2.0.3,<=2.3.3",
    "scipy>=1.11.1,<=1.16.2",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://pyiron.org"
Documentation = "https://pyiron_vasp.readthedocs.io"
Repository = "https://github.com/pyiron/pyiron_vasp"

[project.optional-dependencies]
plot = [
    "matplotlib==3.10.6"
]

[tool.hatch.build]
include = [
    "pyiron_vasp"
]

[tool.hatch.build.hooks.vcs]
version-file = "pyiron_vasp/_version.py"

[tool.hatch.build.targets.sdist]
include = [
    "pyiron_vasp"
]

[tool.hatch.build.targets.wheel]
packages = [
    "pyiron_vasp"
]

[tool.hatch.version]
source = "vcs"
path = "pyiron_vasp/_version.py"

[tool.coverage.run]
omit = ["pyiron_vasp/_version.py", "tests/*"]
command_line = "-m unittest discover tests"
