[project]
name = "reqman4"
version = "0.5.1"
description = "reqman4 (prototype), command 'rq' "
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.2.1",
    "colorama>=0.4.6",
    "httpx>=0.28.1",
    "pyjwt>=2.10.1",
    "python-dotenv>=1.1.1",
    "ruamel-yaml>=0.18.15",
]

[tool.uv]
package = true

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

[project.scripts]
rq = "reqman4.main:command"
reqman4 = "reqman4.main:command"

[project.urls]
Homepage = "https://github.com/manatlan/reqman4"
Repository = "https://github.com/manatlan/reqman4"
Issues = "https://github.com/manatlan/reqman4/issues"


[tool.pytest.ini_options]
addopts = "--cov=src/reqman4 --cov-report=html --cov-report=xml --cov-report=term-missing"

[dependency-groups]
dev = [
    "jsonschema>=4.25.1",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "pytest-cov>=6.2.1",
    "respx>=0.21.0",
]
