[project]
name = "fastapi-autoroutes"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "diskcache>=5.6.3",
    "fastapi>=0.118.0",
    "sqlmodel>=0.0.25",
]
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
