[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "friendly_module_not_found_error"
version = "1.0.3"
description = "Change the message in ModuleNotFoundError"
readme = "README.md"
license = {text = "MIT"}
authors = [
    { name = "Locked-chess-official", email = "13140752715@163.com" }
]
requires-python = ">=3.7"

[project.urls]
Homepage = "https://github.com/Locked-chess-official/friendly_module_not_found_error"
"Bug Reports" = "https://github.com/Locked-chess-official/friendly_module_not_found_error/issues"
Source = "https://github.com/Locked-chess-official/friendly_module_not_found_error"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = [
    "friendly_module_not_found_error",
    "friendly_module_not_found_error.*",
    "wrong_module",
    "wrong_module.*",
    "wrong_child_module",
    "wrong_child_module.*"
]

[project.entry-points."sitecustomize"]
friendly_module_not_found_error = "friendly_module_not_found_error:entry_point"

[project.scripts]
testmodule = "friendly_module_not_found_error.__main__:main"
