[build-system]
requires = ["setuptools>=69.0.3", "setuptools-scm[toml]>=7.1", ]
build-backend = "setuptools.build_meta"

[project]
name = "synerty-peek"
version = "5.1.6"
description = "Peek Platform - Meta Package to install all services"
keywords = ["Peek", "Python", "Platform", "synerty", ]
classifiers = ["Programming Language :: Python :: 3.5", ]
dependencies = ["peek-admin-doc==5.1.6", "peek-admin-app==5.1.6", "peek-agent-service==5.1.6", "peek-core-device==5.1.6", "peek-core-docdb==5.1.6", "peek-core-email==5.1.6", "peek-core-search==5.1.6", "peek-core-user==5.1.6", "peek-core-screen==5.1.6", "peek-field-doc==5.1.6", "peek-field-app==5.1.6", "peek-field-service==5.1.6", "peek-logic-service==5.1.6", "peek-office-doc==5.1.6", "peek-office-app==5.1.6", "peek-office-service==5.1.6", "peek-platform==5.1.6", "peek-plugin-base==5.1.6", "peek-storage-service==5.1.6", "peek-worker-service==5.1.6", "peek-abstract-chunked-index==5.1.6", "peek-abstract-chunked-data-loader==5.1.6", "sphinx", "sphinx-rtd-theme", "sphinx-autobuild", "pytmpdir>=1.0.2", "py-spy", ]
[[project.authors]]
name = "Synerty"
email = "contact@synerty.com"

[project.urls]
Homepage = "https://gitlab.synerty.com/peek/peek"

[tool.pylsp-mypy]
enabled = true
live_mode = true
strict = true

[tool.pycodestyle]
max-line-length = 80

[tool.isort]
profile = "black"

[tool.black]
line-length = 80
target-version = ["py312", ]

[tool.prettier]
printWidth = 80
tabWidth = 4
semi = true
singleQuote = false
trailingComma = "all"
bracketSpacing = true
arrowParens = "avoid"

[tool.setuptools.package-data]

[tool.setuptools.exclude-package-data]

[tool.setuptools.packages.find]
where = [".", ]
namespaces = false
exclude = ["*.tests", "*.tests.*", "tests.*", "tests", ]
