[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "toposkg"
version = "0.1.7"
description = "A Python interface to the ToposKG knowledge graph generation pipeline."
authors = [
    { name="Sergios-Anestis Kefalidis", email="skefalidis@di.uoa.gr" },
    { name="Kostas Plas", email="kplas@di.uoa.gr" }
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.10"
dependencies = ['fsspec', 'pyjedai', 'pandas', 'rich', 'geopandas', 'geojson', 'shapely', 'fiona', 'six', 'pyproj', 'morph_kgc']

[project.optional-dependencies]
tl = ["unsloth"]
fc = ["openai"]
full = ["openai", "unsloth"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["toposkg*"]

[tool.setuptools.package-data]
toposkg = ["jar_libs/*.jar", "scripts/*.sh"]