[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sweetiepy"
version = "1.0.1"
description = "Type 1 Diabetes Data Analysis from DIY Loop system"
authors = [{name = "Michelle Weirathmueller", email = "info@waveformanalytics.com"}]
readme = "README.md"
license = "MIT"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.14.11",
    "matplotlib>=3.10.3",
    "pandas>=2.3.1",
    "pandas-stubs==2.3.0.250703",
    "plotly>=6.2.0",
    "pyarrow>=20.0.0",
    "pymongo>=4.13.2",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.1.1",
    "pytz>=2024.1",
]

[tool.hatch.build.targets.wheel]
packages = ["src/sweetiepy"]

[dependency-groups]
dev = [
    "build>=1.3.0",
    "hatchling>=1.27.0",
    "twine>=6.1.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "ruff>=0.1.0",
    "twine>=6.1.0",
]
