[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "index"
version = "0.5.3.dev2"
authors = [
    { name="Stan Ovchinnikov", email="lishnih@gmail.com" },
]
description = "A lightweight spreadsheet indexing system"
readme = "README.md"
license = "MIT OR LGPL-2.1-or-later"
license-files = ["LICENSE*"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Manufacturing",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Utilities",
]
requires-python = ">=3.6"
dependencies = [
    "openpyxl>=3.0",
    "pyxlsb>=1.0",
    "pymongo>=4.0",
]
[project.optional-dependencies]
obsolete = [
    "xlrd",
]
dotenv = [
    "python-dotenv",
]
all = [
    "index[obsolete]",
    "index[dotenv]",
]

[project.urls]
Homepage = "https://github.com/ndtfy/index.next"
Issues = "https://github.com/ndtfy/index.next/issues"
Source = "https://gitflic.ru/project/stan/index"

[project.scripts]
index = "index.cli:main"

[tool.flit.module]
name = "index"

[tool.flit.sdist]
include = [
    "docs/",
    "examples/",
    "tests/",
]
exclude = [
    "docs/_build/",
    "src/start.py",
    ".gitignore",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "error",
]

[tool.coverage.run]
branch = true
source = ["index", "tests"]

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.mypy]
python_version = "3.8"
files = ["src/index"]
show_error_codes = true
pretty = true
strict = true

[[tool.mypy.overrides]]
module = [
    "asgiref.*",
    "dotenv.*",
    "cryptography.*",
    "importlib_metadata",
]
ignore_missing_imports = true

[tool.pyright]
pythonVersion = "3.8"
include = ["src/index"]
typeCheckingMode = "basic"

[tool.ruff]
src = ["src"]
fix = true
show-fixes = true
output-format = "full"

[tool.ruff.lint]
select = [
    "B",  # flake8-bugbear
    "E",  # pycodestyle error
    "F",  # pyflakes
    "I",  # isort
    "UP",  # pyupgrade
    "W",  # pycodestyle warning
]

[tool.ruff.lint.isort]
force-single-line = true
order-by-type = false
