[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "osmose_presets"
version = "0.1.5"
description = ""
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Carl Caulkett", email = "carl.caulkett@gmail.com" }
]
dependencies = [
  "textual==6.1.0",
  "textual-dev==1.7.0",
  "textual[syntax]==6.1.0",
  "python-rtmidi>=1.5.8",
  "mido==1.3.3",
]

[project.scripts]
osmose_presets = "osmose_presets.app:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
indent-width = 3
line-length = 160
target-version = "py310"

[tool.ruff.format]
indent-style = "space"
# skip-magic-trailing-comma = true

[tool.uv]
dev-dependencies = [
   "textual==6.1.0",
   "textual-dev==1.7.0",
   "textual[syntax]==6.1.0",
   "ruff>=0.11.8",
]
