[project]
name = "pygameforbabies"
version = "0.0.3"
description = "simple pygame"
authors = [{ name="Annes", email="anneswidow@gmail.com" }]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.7"

[build-system]
requires = ["setuptools>=61.0","pygame","opencv-python"]
build-backend = "setuptools.build_meta"
