[build-system]
requires = [ "setuptools>=69.0.3", "setuptools-scm[toml]>=7.1",]
build-backend = "setuptools.build_meta"

[project]
name = "peek-field-service"
version = "5.1.6"
description = "Peek Field Service - where Peek Field App is served"
keywords = [ "Peek", "Python", "Platform", "synerty",]
classifiers = []
dependencies = [ "peek-plugin-base==5.1.6", "peek-platform==5.1.6", "peek-field-app==5.1.6", "peek-field-doc==5.1.6",]
[[project.authors]]
name = "Synerty"
email = "contact@synerty.com"

[project.urls]
Homepage = "https://github.com/Synerty/peek-field-service"

[project.scripts]
run_peek_field_service = "peek_field_service.run_peek_field_service:main"
run_peek_field_service_build_only = "peek_field_service.run_peek_field_service_build_only:main"
run_peek_field_service_offline = "peek_field_service.run_peek_field_service_offline:main"
winsvc_peek_field_service = "peek_field_service.winsvc_peek_field_service:main"

[tool.pylsp-mypy]
enabled = true
live_mode = true
strict = true

[tool.pycodestyle]
max-line-length = 80

[tool.isort]
profile = "black"

[tool.black]
line-length = 80
target-version = [ "py312",]

[tool.prettier]
printWidth = 80
tabWidth = 4
semi = true
singleQuote = false
trailingComma = "all"
bracketSpacing = true
arrowParens = "avoid"

[tool.setuptools.package-data]
"*" = [ "webpack.config.js", "karma.conf.js", "protractor.conf.js",]

[tool.setuptools.exclude-package-data]
"*" = [ "__pycache__", "platforms", "dist", "*.pyc", "*.js", "*.js.map", "*.lastHash",]

[tool.setuptools.packages.find]
where = [ ".",]
namespaces = false
exclude = [ "*.tests", "*.tests.*", "tests.*", "tests", "*.node_modules", "*.node_modules.*", "node_modules.*", "node_modules",]
