[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mindforge-ml"
version = "0.1.8"
description="An open-source machine learning library for research and production, offering unified tools across deep learning, NLP, computer vision, reinforcement learning, and predictive analytics."
authors = [
  { name="Godsave Kawurem", email="godsaveogbidor@gmail.com" }
]
license = { text = "MIT" }
readme = "README.md"
dependencies = [
    "numpy",
    "pandas",
    "transformers",
    "scikit-learn",
    "matplotlib",
    "seaborn",
    "torch",
    "spacy"
]
keywords = ["machine learning", "AI", "scikit-learn", "deep learning", "pytorch", "mindforge"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]


requires-python = ">=3.8"

[tool.setuptools]
packages = ["mindforge_ml"]
include-package-data = true



[project.urls]
"Homepage" = "https://github.com/Perfect-Aimers-Enterprise/mindforge"
"Bug Tracker" = "https://github.com/Perfect-Aimers-Enterprise/mindforge/issues"