[project]
name = "cursh"
version = "1.0.1"
authors = [
  { name="Tanjim Kamal", email="tanjimkamal1@gmail.com" },
]
description = "Protect your Linux PC from viruses using a safer alternative to `curl ... | sh` or `wget ... | sh`"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: Unix",
    "Development Status :: 4 - Beta",
    "Topic :: Security"
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/itzmetanjim/cursh"
Issues = "https://github.com/itzmetanjim/cursh/issues"

[project.scripts]
cursh = "cursh.main"