[project]
name = "mirmod"
version = "5.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "setuptools",
    "dill",
    "networkx",
    "matplotlib",
    "plotly",
    "pyyaml",
    "asyncio",
    "asyncssh",
    "mysql-connector-python==8.0.28",
    "pandas",
    "numpy",
    "pillow",
    "requests",
    "filesplit",
    "tabulate",
    "ipython",
    "lxml",
    "niquests",
    "nest_asyncio"
]

[dependency-groups]
dev = [
    "poethepoet>0",
    "pytest>0",
    "ruff>0",
]

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
