[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "intradev"
version = "0.1.1"
authors = [
  { name="Aiden McDougal", email="lilsteeler03@gmail.com" }
]
description = "tool to accelerate creation of simple IO Python GUIs."
readme = "README.md"
requires-python = ">=3.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "customtkinter>=5.2"
]

[project.urls]
Homepage = "https://github.com/asm3002/intradev"
Issues = "https://github.com/asm3002/intradev/issues"

[tool.hatch.build]
exclude = [
  "/.venv",
  "/dist",
  "/build",
  "**/__pycache__",
  "**/*.pyc",
  ".DS_Store",
  ".git",
  ".gitignore",
  ".gitattributes",
  "*.ipynb_checkpoints",
  "test.py"
]

[tool.hatch.build.targets.wheel]
exclude = [
  ".venv/",
  "dist/",
  "build/",
  ".git/",
  ".gitignore",
  ".gitattributes",
  ".DS_Store",
  "**/__pycache__/",
  "**/*.pyc",
  "**/*.pyo",
  "*~",
  "*.ipynb_checkpoints",
  "test.py"
]
