[project]
name = "technical-analysis-mcp"
version = "0.7.1"
description = "A Python package for technical analysis of financial markets"
authors = [
    {name = "libin", email = "binlish81@qq.com"}
]
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Financial and Insurance Industry",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
]
dependencies = [
    "akshare",
    "pandas",
    "openai",
    "backtrader",
    "mcp>=1.13.0",
    "fastapi",
    "scipy"
]

[project.scripts]
technical-analysis-mcp = "technical_analysis.main:main"
technical-analysis-http = "technical_analysis.http_server:app"

[tool.setuptools]
packages = ["technical_analysis"]