[project]
name = "donnes-des-sous-nawel"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "NawelMera", email = "nawel.merabet@ig2i.centralelille.fr" }
]
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
]

[project.scripts]
donnes-des-sous-nawel = "donnes_des_sous_nawel:main"

[build-system]
requires = ["uv_build>=0.8.19,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black>=25.9.0",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.13.2",
]
