[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[project]
name = "dcnr-scheduler"            # <-- change to a unique name on (Test)PyPI
version = "1.0.0"
description = "Scheduling python functions for execution."
readme = "README.md"
requires-python = ">=3.9"
authors = [{ name = "Rocky Wilson", email = "rocky.wilson@gopal.home.sk" }]
license = { text = "MIT" }
keywords = ["scheduler", "python"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

# # Optional console entry point: installs a `hello` command
# [project.scripts]
# hello = "scheduler_pkg.core:main"

[project.urls]
Homepage = "https://dcnr-utilities.com"

[tool.hatch.build.targets.wheel]
packages = ["scheduler_pkg"]
