[project]
name = "flask-confluent-kakfa"
version = "0.1.0-a"
description = "A simple Flask extension for integrating Confluent Kafka."
authors = [{name = "River", email = "vicente.marcal@gmail.com"}]
license = {text = "GPL+v3"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "confluent-kafka>=2.11.1",
]


[project.scripts]
flask-confluent-kafka = "flask-confluent-kafta:flaks_confluent_kafka"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
