[project]
name = "meow-package"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Augustin MORICEAU", email = "augustin.moriceau@orange.fr" }
]
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pytest>=8.4.2",
]

[project.scripts]
meow-package = "meow_package:main"

[build-system]
requires = ["uv_build>=0.8.19,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black>=25.9.0",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.13.1",
]
