[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tianxiadatong_qq_robot"            # 库名
version = "0.1.8"
description = "tianxiadatong_qq_robot SDK"
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
include = ["tianxiadatong_qq_robot*"]

[tool.setuptools.package-data]
tianxiadatong_qq_robot = ["*.pyd", "*.dll","config.json"]   # 按实际扩展名写


#打包上传直接终端运行
#Remove-Item -Recurse -Force build, dist, *.egg-info
#python -m build
#pip install dist\tianxiadatong_qq_robot-0.1.2-py3-none-any.whl --force-reinstall
#twine upload dist/*

#项目地址： https://pypi.org/project/tianxiadatong-qq-robot/
#账号：tianxiadatong
#密码：txdt8888
#邮箱：caihaixiong@tianxiadatong.net.cn

#API token:
#pypi-AgEIcHlwaS5vcmcCJDYzMzRjNmI1LWU5ZmYtNDVlNi05ZmYzLTMyNjEwNGRlMWVkOAACKlszLCIwMDAwYjM0Yi1hODIyLTRiMjgtODBiOC1mMWQyOGYxMmUxNDUiXQAABiDq4k7_pSs-Rix-K7z5u8Hkh6SCFCGEoTeffxx6Roiggw

#PyPI recovery codes
#5fc161af1bbf3b70
#9aafe32e3876049f
#24212f046952f284
#9b83a28024ee329e
#5ac6477242517382
#23083c887314e179
#a3122a63040facd6
#82af1e0c9ff227ed
