[tool.poetry]
name = "dt-misc"
version = "0.2.19"
description = "Misc. utility packages (geoloc, weather, sound, ...)"
authors = ["Al DAmico <JavaWiz1@hotmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/JavaWiz1/dt-misc"
keywords = ["python", "dt-tools"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
packages = [
    { include = "dt_tools" },
]
include = ["CHANGELOG.md"]

[tool.poetry.dependencies]
python = "^3.10"
loguru = "*"
gtts = "^2.5.2"
# dt-foundation = {path = "../dt-foundation", develop = true }
# dt-net = {path = "../dt-net", develop = true }
dt-foundation = "*"
dt-net = "*"
timezonefinder = "*"
tzdata = { version="*", platform="win32" } 
pyaudio = "^0.2.14"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "piwheels"
url = "https://www.piwheels.org/simple"
priority = "supplemental"


[tool.poetry.group.dev.dependencies]
# sphinx-rtd-theme = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
