[project]
name = "numworks_env"
version = "0.1.1"
description = "Port of the NumWorks python environment for PC"
authors = [
    {name = "spxnso",email = "146754550+spxnso@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "keyboard (>=0.13.5,<0.14.0)",
    "matplotlib (>=3.10.6,<4.0.0)",
    "numpy (>=2.3.3,<3.0.0)"
]

[tool.poetry]
packages = [{include = "numworks_env"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
