[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aer-gel-annotate"
version = "0.1.8"
description = "GUI + pipeline for gel well detection, ladder reading, and PCR band annotation."
readme = "README.md"
license = {text = "MIT"}
authors = [{name = "Manan Shah", email = "manan.b.shah@gmail.com"}]
requires-python = ">=3.9"
dependencies = [
  "numpy>=1.24",
  "scipy>=1.10",
  "scikit-image>=0.22",
  "matplotlib>=3.8",
  "PyQt5>=5.15",
  "tifffile>=2023.7.10",
  "imagecodecs"
]

[project.optional-dependencies]
windows = ["pywin32>=306"]     # for creating a proper .lnk shortcut on Windows


[tool.setuptools]
packages = ["annotation", "annotation.gui", "annotation.assets", "annotation.scripts"]

[tool.setuptools.package-data]
annotation = ["assets/*"]

[project.scripts]
gel-annotate = "annotation.gui.gel_gui_wrapper:main"          # runs the GUI
gel-annotate-cli = "annotation.cli_main:main"                 # (optional) CLI
gel-annotate-shortcut = "annotation.scripts.shortcuts:main"   # creates a desktop/start-menu shortcut
