[build-system]
requires = ["setuptools>=69.0.3", "setuptools-scm[toml]>=7.1", ]
build-backend = "setuptools.build_meta"

[project]
name = "peek-platform"
version = "5.1.6"
description = "Peek Platform - Common code that runs for Peek services"
keywords = ["Peek", "Python", "Platform", "synerty", ]
classifiers = []
dependencies = ["pip >= 21.0", "virtualenv >= 15.1.0", "twine", "Cython >= 0.21.1", "Twisted[tls,conch]", "pyOpenSSL", "pyasn1 >= 0.1.9", "pyasn1-modules >= 0.0.8", "psycopg", "psycopg-c", "SQLAlchemy", "alembic >= 0.8.7", "python-dateutil >= 2.6.0", "Pygments >= 2.0.1", "watchdog >= 0.8.3", "pycryptodome", "cryptography", "peek-plugin-base==5.1.6", "peek-core-device==5.1.6", "peek-core-email==5.1.6", "psutil", "pexpect", "Shapely >= 1.5.16; platform_system=='Linux'", "future; platform_system=='Linux'", "coverage >= 4.2", "mock >= 2.0.0"]
[[project.authors]]
name = "Synerty"
email = "contact@synerty.com"

[project.urls]
Homepage = "https://github.com/Synerty/peek-office-service"

[project.scripts]
run_peek_office_service = "peek_office_service.run_peek_office_service:main"
run_peek_office_service_build_only = "peek_office_service.run_peek_office_service_build_only:main"
winsvc_peek_office_service = "peek_office_service.winsvc_peek_office_service:main"

[tool.pylsp-mypy]
enabled = true
live_mode = true
strict = true

[tool.pycodestyle]
max-line-length = 80

[tool.isort]
profile = "black"

[tool.black]
line-length = 80
target-version = ["py312", ]

[tool.prettier]
printWidth = 80
tabWidth = 4
semi = true
singleQuote = false
trailingComma = "all"
bracketSpacing = true
arrowParens = "avoid"

[tool.setuptools.package-data]

[tool.setuptools.exclude-package-data]

[tool.setuptools.packages.find]
where = [".", ]
namespaces = false
exclude = ["*.tests", "*.tests.*", "tests.*", "tests", ]
