[project]
name = "notes-mcp"
version = "0.1.0"
description = "MCP for managing markdown notes with YAML frontmatter"
authors = [
    {name = "Edvard LindelÃ¶f", email = "edvardlindelof@gmail.com"},
]
requires-python = ">= 3.13"
dependencies = [
    "fastmcp>=2.12.3",
    "pyyaml>=6.0.2",
]

[project.scripts]
notes-mcp = "server"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
only-include = ["server.py"]
