[project]
name = "huibiao-framework"
version = "1.0.17.20250929"
description = "Huibioa framework."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.13",
    "fastapi>=0.116.1",
    "loguru>=0.7.3",
    "miniopy-async>=1.23.2",
    "prometheus-client>=0.22.1",
    "pydantic>=2.11.7",
    "pytest>=8.4.2",
    "python-dotenv>=1.1.1",
]
