[tool.poetry]
name = "react-tk"
version = "0.2.2"
description = "Tkinter UI with react principles."
authors = ["GregRos <gregros@gregros.dev>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
typeguard = "^4.4.0"
pywin32 = "^311"
funcy = "^2.0"
funcy-typing = "^2.0.8"
pytest = "^8.4.2"
expression = "^5.6.0"
[tool.pytest.ini_options]
testpaths = "test"
python_functions = "it_*"
python_classes = ["*_Test"]
python_files = ["*.py"]
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
