[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "monkey.dao"
version = "2.0.0b1"
description = "Simple Data Access Object pattern implementation."
readme = "README.md"
license-files = ["LICENSE"]

authors = [
    { name = "Xavier ROY", email = "xavier@monkey-python.org" }
]
maintainers = [

]

requires-python = ">= 3.10"

dependencies = [

]

classifiers = [
    'Programming Language :: Python',
    'Development Status :: 4 - Beta',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3.10',
    'Topic :: Software Development :: Libraries :: Python Modules',
    'Intended Audience :: Developers'
]

keywords = ["dao", "data-access-object", "persistence"]

[project.urls]
Homepage = "https://dao.monkey-python.org"
Documentation = "https://dao.monkey-python.org/API"
Repository = "https://bitbucket.org/monkey-python/monkey-dao/"
Chgangelog = "https://dao.monkey-python.org/changelog/"

[dependency-groups]
doc = [
    "mkdocs",
    "mkdocs-autorefs",
    "mkdocs-material",
    "mkdocs-macros-plugin",
    "mkdocstrings[python]",
    "mike"
]
test = [
    "pytest",
    "mongomock"
]
tools = [
    "black",
    "pip-tree",
    "ruff"
]
all = [
    { include-group = "doc" },
    { include-group = "test" },
    { include-group = "tools" }
]

[tool.distutils.egg_info]
egg_base = "."

[tool.setuptools]
package-dir = { "" = "src/main/python" }

[tool.setuptools.packages.find]
where = ["src/main/python"]
namespaces = true
