[build-system]
requires = [ "setuptools>=69.0.3", "setuptools-scm[toml]>=7.1",]
build-backend = "setuptools.build_meta"

[project]
name = "peek-plugin-gis-diagram"
version = "5.1.6"
description = "Peek Plugin GisDiagram - geographic digram of Peek"
keywords = [ "Peek", "Python", "Platform", "synerty",]
classifiers = []
dependencies = [ "peek-plugin-base==5.1.6",]
[[project.authors]]
name = "Synerty"
email = "contact@synerty.com"

[project.urls]
Homepage = "https://github.com/Synerty/peek-plugin-gis-diagram"

[tool.pylsp-mypy]
enabled = true
live_mode = true
strict = true

[tool.pycodestyle]
max-line-length = 80

[tool.isort]
profile = "black"

[tool.black]
line-length = 80
target-version = [ "py312",]

[tool.prettier]
printWidth = 80
tabWidth = 4
semi = true
singleQuote = false
trailingComma = "all"
bracketSpacing = true
arrowParens = "avoid"

[tool.setuptools.package-data]
"*" = [ "webpack.config.js", "karma.conf.js", "protractor.conf.js",]

[tool.setuptools.exclude-package-data]
"*" = [ "__pycache__", "platforms", "dist", "*.pyc", "*.js", "*.js.map", "*.lastHash",]

[tool.setuptools.packages.find]
where = [ ".",]
namespaces = false
exclude = [ "*.tests", "*.tests.*", "tests.*", "tests", "*.node_modules", "*.node_modules.*", "node_modules.*", "node_modules",]
