[build-system]
requires = [ "setuptools>=69.0.3", "setuptools-scm[toml]>=7.1",]
build-backend = "setuptools.build_meta"

[project]
name = "peek-plugin-base"
version = "5.1.6"
description = "Peek Plugin Base - dependencies that an Peek plugin needs"
keywords = [ "Peek", "Python", "Platform", "synerty",]
classifiers = []
dependencies = [ "SQLAlchemy", "alembic >= 0.8.7", "GeoAlchemy2", "Twisted[tls,conch]", "json-cfg-rw", "vortexpy", "pytmpdir", "txhttputil", "SOAPpy-py3 >= 0.52.30", "wstools-py3 >= 0.54.2", "txsuds-py3 >= 0.5.9", "reactivex>=4.0.4", "pytz", "tzlocal", "patch-ng >=1.17.4", "setproctitle",]
[[project.authors]]
name = "Synerty"
email = "contact@synerty.com"

[project.urls]
Homepage = "https://github.com/Synerty/peek-plugin-base"

[tool.pylsp-mypy]
enabled = true
live_mode = true
strict = true

[tool.pycodestyle]
max-line-length = 80

[tool.isort]
profile = "black"

[tool.black]
line-length = 80
target-version = [ "py312",]

[tool.prettier]
printWidth = 80
tabWidth = 4
semi = true
singleQuote = false
trailingComma = "all"
bracketSpacing = true
arrowParens = "avoid"

[tool.setuptools.package-data]

[tool.setuptools.exclude-package-data]

[tool.setuptools.packages.find]
where = [ ".",]
namespaces = false
exclude = [ "*.tests", "*.tests.*", "tests.*", "tests",]
