[build-system]
requires = [
  "setuptools>=61.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "rda_python_dbms"
version = "1.0.26"
authors = [
  { name="Zaihua Ji", email="zji@ucar.edu" },
]
description = "RDA Python Package to manage PostreSQL databases"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
]
dependencies = [
  "rda_python_common",
]

[project.urls]
"Homepage" = "https://github.com/NCAR/rda-python-dbms"

[project.scripts]
pgddl = "rda_python_dbms.pgddl:main"
pgseq = "rda_python_dbms.pgseq:main"
pgbackup = "rda_python_dbms.pgbackup:main"
pgdbdump = "rda_python_dbms.pgdbdump:main"
pgdbrestore = "rda_python_dbms.pgdbrestore:main"
pgchksum = "rda_python_dbms.pgchksum:main"
pgcmptables = "rda_python_dbms.pgcmptables:main"
pgschema = "rda_python_dbms.pgschema:main"
