[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "peerpyrtc"
version = "0.2.1"
description = "A Python-based WebRTC signaling and data channel library"
readme = { file = "README.md", content-type = "text/markdown" }
license = { text = "MIT" }
authors = [{ name="Sagnik", email="sagnify2022@gmail.com" }]
requires-python = ">=3.10"
dependencies = [
    "aiortc>=1.5.0"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["peerpyrtc*"]  # <-- ensures all subpackages are included

[tool.setuptools]
include-package-data = true  # <-- include files listed in MANIFEST.in