[project]
name = "kbench-controls"
version = "0.7.0"
description = "Default template for PDM package"
authors = [
    { name = "Vincent Foriel", email = "vincent.foriel@gmail.com" },
    { name = "mmartinod", email = "ma.martinod@free.fr" },
    { name = "", email = "" },
]
dependencies = [
    "numpy",
    "pyserial",
    "pyyaml",
    "toml>=0.10.2",
]
requires-python = "==3.12.*"
readme = "README.md"

[project.license]
text = "MIT"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = []

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = [
    "src",
]
include = [
    "kbench*",
    "bmc*",
]

[tool.setuptools.package-data]
bmc = [
    "*.so",
]
