[project]
name = "victoriabank-mia-sdk"
version = "1.1.4"
authors = [{ name = "Alexander Minza" }]
description = "Python SDK for Victoriabank MIA API"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["httpx"]
keywords = [
  "victoriabank",
  "moldova",
  "mia",
  "qr",
  "payments",
  "api",
  "sdk",
  "python",
]
classifiers = [
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
license = "GPL-3.0-or-later"

[project.urls]
Homepage = "https://github.com/alexminza/victoriabank-mia-sdk-python"
Issues = "https://github.com/alexminza/victoriabank-mia-sdk-python/issues"
Repository = "https://github.com/alexminza/victoriabank-mia-sdk-python"
Documentation = "https://test-ipspj.victoriabank.md"
