[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "rui_utils"
packages = [{include = "rui_utils"}]
version = "0.1.0"
description = "ADDME"
readme = "README.md"
license = "MIT"
authors = ["Chen-Rui Xia <xiachenrui@mail.cbi.pku.edu.cn>"]
keywords = ["ADDME"]
homepage = "https://github.com/xiachenrui/rui_utils"
documentation = "https://github.com/xiachenrui/rui_utils"
repository = "https://github.com/xiachenrui/rui_utils"
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Bio-Informatics"
]


[tool.poetry.dependencies]
python = ">=3.10"
loguru = "*"
scanpy = "*"
pynvml = "*"
addict = "*"
faiss-cpu = "*"
annoy = "*"
pyyaml = "*"
rapids_singlecell = "*"

[tool.pyright]
include = ["rui_utils"]
exclude = ["**/conda", "**/__pycache__", "**/.**"]
ignore = ["resource/"]
typeCheckingMode = "off"
reportCallIssue = 'warning'


[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
source = ["rui_utils"]

[tool.coverage.report]
show_missing = true

[tool.jupytext]
formats = "ipynb,py:percent"

[tool.black]
line-length = 100

[tool.flake8]
max-line-length = 100

[tool.isort]
line_length = 100
