[slots]
000 = ["Gainfully_fun.bin", "Always_On.bin"]
001 = ["Rephrase_v1_0.bin", "Angry_robots.bin"]
002 = ["SAMPLE.bin", "Elemental_Ring.bin"]
003 = ["Loop_Noodle-680ef8977c75f.bin"]
004 = ["Tiny_Orchestra.bin"]
005 = ["Always_On.bin"]
006 = ["Angry_robots.bin"]
007 = ["Elemental_Ring.bin"]
008 = ["4_track_punk.bin"]
009 = ["JohannLooper_V3.bin"]
010 = ["loop_forest.bin"]
011 = ["80s_night.bin"]
012 = ["GrainBox02-680efaaca37b8.bin"]
013 = ["Impala.bin"]
014 = ["Abyss_Water.bin"]
015 = ["Hi_gain_hijinks.bin"]
016 = ["Abyss_Water_zebu.bin"]
017 = ["Spaced.bin"]
018 = ["Swirly.bin"]
019 = ["Lo_fi_fun.bin"]
020 = ["Get_subby.bin"]
021 = ["Midas_Hand-6407ed775dbfb.bin"]
022 = ["Mix_n_Match.bin"]
023 = ["Angelic.bin"]
024 = ["JohannLooper.bin"]
025 = ["JohannLooper1_1.bin"]
026 = ["We_Could_Paint.bin"]
027 = ["Echolalia-682cd0163ad3b.bin"]
028 = ["Woozy.bin"]
029 = ["Signal_strength.bin"]
030 = ["Swinging_phaser.bin"]
031 = ["Dirty_space.bin"]
032 = ["Clean_gain.bin"]
033 = ["Reverse_Mode_Z-677db6ccb0d94.bin"]
034 = ["Grub_brain.bin"]
035 = ["Classic_amp.bin"]
036 = ["Cosmic_fuzz.bin"]
037 = ["Delay_ay_ay.bin"]
038 = ["Stereo_depths.bin"]
039 = ["Betamax.bin"]
040 = ["Orchestral_v3-67b7f48a2d158.bin"]
041 = ["Total_Random-680042cc3340b.bin"]
042 = ["Broken_ghosts.bin"]
043 = ["Passing_through.bin"]
044 = ["DFAM.bin"]
045 = ["Smashed_snarl.bin"]
046 = ["Wash.bin"]
047 = ["Shine.bin"]
048 = ["Grungy.bin"]
049 = ["Ambient_repeats.bin"]
050 = ["Parallel_air.bin"]
051 = ["Recombinatrix.bin"]
052 = ["RecombinatrixV2.bin"]
053 = ["HAINO_Glitch_V2.bin"]
054 = ["prevarication-6851c36ae44ab.bin"]
055 = ["Loop_Van_Winkle.bin"]
056 = ["JohannLooper_V2.bin"]
057 = ["Fime_tlies-67584b13b63f8.bin"]
058 = ["GOLDFINGER.bin"]
059 = ["GOLDFINGER 2.bin"]
060 = ["Phrase_Recorder.bin"]
