[package]
name = "pindakaas"
description = "Encoding Integer and Pseudo Boolean constraints into CNF"
version = "0.2.1"

authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true

readme = "README.md"

[package.metadata.docs.rs]
all-features = true

[dependencies]
itertools = "0.14"
rustc-hash = "2.0"
rangelist = "0.3.1"

# Dynamically load solver libraries (through IPASIR interfaces)
libloading = { version = "0.8", optional = true }
# Optional encoding tracing capabilities
tracing = { workspace = true, optional = true }

# Optional Solver Interfaces
pindakaas-cadical = { version = "0.2.0", path = "../pindakaas-cadical", optional = true }
pindakaas-intel-sat = { version = "0.2.0", path = "../pindakaas-intel-sat", optional = true }
pindakaas-kissat = { version = "0.2.0", path = "../pindakaas-kissat", optional = true }
splr = { version = "0.17", optional = true }

[dev-dependencies]
expect-test = "1.5.0"
pindakaas-cadical = { path = "../pindakaas-cadical" }
traced_test = { path = "../traced_test" }
tracing = { workspace = true }

[features]
cadical = ["pindakaas-cadical"]
default = ["cadical"]
external-propagation = ["cadical"]
intel-sat = ["pindakaas-intel-sat"]
kissat = ["pindakaas-kissat"]

[lints]
workspace = true
