[build-system]
requires = ["flit_core >=3.2,<4"]

build-backend = "flit_core.buildapi"

[project]
name = "qforms"
version="0.0.3"
authors = [
    {name = "Jo\u00e3o Alvim", email = "joaoalvim179@proton.me"},
    {name = "JJoao", email ="jj@di.uminho.pt"}] 

dynamic = ["description"]
readme = "README.md"
keywords = ["forms","flask","privacy" ]

dependencies = [
    "flask",
    "waitress",
    "pyyaml",
    "jjcli"
]

[project.scripts]
qforms = "qforms:main"


[project.urls]
repository = "https://github.com/jotaalvim/qforms"
"Bug Tracker" = "https://github.com/jotaalvim/qforms/issues"
