[tool.poetry]
name = "ml_eval_viz"
version = "0.2.0"
description = "A custom python package for Machine Learning model evaluation and visualization."
authors = ["Vaibhav Kiran Ghaisas"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.4"
pandas = "2.2.2"
scikit-learn = "1.5.1"
numpy = "^2.3.2"
matplotlib = "^3.10.5"


[tool.poetry.group.dev.dependencies]
pytest = "8.2.2"
jupyterlab = "4.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]