[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "kclasses"
version = "0.1.4"
authors = [
    {name = "KeVeon White", email = "keveonwhite@gmail.com"},
]
description = "Extensions of built-in Python classes"
readme = "README"
requires-python = ">=3.10"
license = "Unlicense"
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]

[project.urls]
Homepage = "https://github.com/AMS0x2A/KClasses"
Issues = "https://github.com/AMS0x2A/KClasses/issues"
