[project]
name = "corpus-judge"
description = "Cleaning, setting Justices"
version = "0.2.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "pydantic >= 2.11",
  "pyyaml >= 6.0.3",
  "unidecode >= 1.4",
  "sqlite-utils >= 3.38",
]

[dependency-groups]
dev = [
    "jupyter >= 1.1.1",
    "notebook >= 7.4.3",
    # docs
    "mkdocs >= 1.6.1",
    "mkdocs-material >= 9.6.20",
    "mkdocstrings[python] >= 0.30.1",
      # testing
    "pytest >= 8.4",
    "pytest-cov >= 5.0",
    "pytest-datadir >= 1.5",
]

[tool.pytest.ini_options]
minversion = "8.4"
addopts = "-ra -q -vv --cov --doctest-modules"
testpaths = ["src", "tests"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
ignore = ["F401", "F403"]
fixable = ["F", "E", "W", "I001"]
select = ["F", "E", "W", "I001"]
