[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 61.0"]

[project]
authors = [
  {name = "(Leslie) Yu Chen", email = "leslie.yuchen666@gmail.com"},
  {name = "Roberto Rocchetta", email = "roberto.rocchetta88@gmail.com"},
  {name = "Ioanna Ioannou", email = "Ioanna.Ioannou@liverpool.ac.uk"},
  {name = "Scott Ferson", email = "sandp8@gmail.com"},
]

dependencies = [
  "matplotlib",
  "numpy",
  "pandas",
  "seaborn",
  "Pint",
  "pymongo",
  "pymoo",
  "scipy >=1.15, <1.15.2",
  "tqdm",
  "pytest",
  "bayesian-optimization",
  "geneticalgorithm",
  "statsmodels >=0.14, <0.15", # Verified 0.14.4 compatibility
  "jax==0.4.35",
  "SALib",
]
description = "Rigorous computation with Uncertain Number in Python"
license = {text = "MIT License"}
maintainers = [
  {name = "(Leslie) Yu Chen", email = "leslie.yuchen666@gmail.com"},
]
name = "pyuncertainnumber"
readme = "README.md"
requires-python = ">= 3.11"
version = "0.0.20"

[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["src"] # ["."] by default   

[project.urls]
Documentation = "https://pyuncertainnumber.readthedocs.io/en/latest/index.html"
Homepage = "https://github.com/leslieDLcy/PyUncertainNumber"
