[project]
authors = [
    { name = "Zebedee Nicholls", email = "zebedee.nicholls@climate-resource.com" },
]
requires-python = ">=3.9"
dependencies = [
    "scitools-iris>=3.0",
    "netcdf4>=1.0",
    "numpy<2.0",
    "cfchecker>=4.1.0",
    "cftime",
    "attrs",
    "cattrs",
    "cf-xarray",
    "loguru",
    "ncdata",
    "pandas",
    "pint",
    "pint-xarray",
    "pooch",
    "tqdm",
    "typer",
    "typing-extensions",
    "validators",
    "xarray",
]
name = "input4mips-validation"
version = "0.20.1"
description = "Validation of input4MIPs data (checking file formats, metadata etc.)."
readme = "README.md"

[project.license]
text = "BSD-3-Clause"

[project.optional-dependencies]
loguru-config = [
    "loguru-config",
]
dev = [
    "pre-commit>=3.7.1",
    "mypy>=1.10.1",
    "towncrier>=23.11.0,<24",
    "packaging>=24.1.0",
    "pandas-stubs>=2.2.2.240603",
    "tomli>=2.0.1",
    "types-tqdm>=4.66.0.20240417",
    "liccheck>=0.9.2,<0.10",
    "setuptools>=70.0.0",
    "pip>=24.2",
    "loguru>=0.7.3",
    "netcdf4>=1.7.2",
]
docs = [
    "mkdocs>=1.6.0",
    "mkdocstrings[python]>=0.25.0",
    "mkdocs-material>=9.5.0",
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-literate-nav>=0.6.1",
    "mkdocs-section-index>=0.3.9",
    "mkdocs-autorefs>=1.0.1",
    "mkdocs-jupyter>=0.25.1",
    "myst-nb>=1.1.1",
    "jupyterlab>=4.2.0",
    "jupytext>=1.16.3",
]
notebooks = [
    "jupyterlab>=4.2.0",
    "jupytext>=1.16.3",
]
tests = [
    "pytest>=8.2.2",
    "coverage>=7.6.0",
    "pytest-cov>=5.0.0",
    "pytest-regressions>=2.5",
]
locked = [
    "antlr4-python3-runtime==4.7.2",
    "attrs==24.3.0",
    "cartopy==0.23.0",
    "cattrs==24.1.2",
    "certifi==2024.12.14",
    "cf-units==3.2.0",
    "cf-xarray==0.9.4",
    "cfchecker==4.1.0",
    "cftime==1.6.4.post1",
    "cfunits==3.3.7",
    "charset-normalizer==3.4.1",
    "click==8.1.8",
    "cloudpickle==3.1.0",
    "colorama==0.4.6",
    "contourpy==1.3.0",
    "cycler==0.12.1",
    "dask==2024.8.0",
    "dask[array]==2024.8.0",
    "exceptiongroup==1.2.2 ; python_version < \"3.11\"",
    "flexcache==0.3",
    "flexparser==0.4",
    "fonttools==4.55.3",
    "fsspec==2024.12.0",
    "future==1.0.0",
    "idna==3.10",
    "importlib-metadata==8.5.0",
    "importlib-resources==6.4.5 ; python_version < \"3.10\"",
    "jinja2==3.1.5",
    "kiwisolver==1.4.7",
    "locket==1.0.0",
    "loguru==0.7.3",
    "markdown-it-py==3.0.0",
    "markupsafe==3.0.2",
    "matplotlib==3.9.4",
    "mdurl==0.1.2",
    "ncdata==0.1.1",
    "netcdf4==1.7.2",
    "numpy==1.26.4",
    "packaging==24.2",
    "pandas==2.2.3",
    "partd==1.4.2",
    "pillow==11.0.0",
    "pint==0.24.4",
    "pint-xarray==0.4",
    "platformdirs==4.3.6",
    "pooch==1.8.2",
    "pygments==2.18.0",
    "pyparsing==3.2.0",
    "pyproj==3.6.1",
    "pyshp==2.3.1",
    "python-dateutil==2.9.0.post0",
    "pytz==2024.2",
    "pyyaml==6.0.2",
    "requests==2.32.3",
    "rich==13.9.4",
    "scipy==1.13.1",
    "scitools-iris==3.8.1",
    "shapely==2.0.6",
    "shellingham==1.5.4",
    "six==1.17.0",
    "toolz==1.0.0",
    "tqdm==4.67.1",
    "typer==0.15.1",
    "typing-extensions==4.12.2",
    "tzdata==2024.2",
    "urllib3==2.3.0",
    "validators==0.34.0",
    "win32-setctime==1.2.0 ; sys_platform == \"win32\"",
    "xarray==2024.7.0",
    "xxhash==3.5.0",
    "zipp==3.21.0",
]
loguru-config-locked = [
    "colorama==0.4.6",
    "loguru==0.7.3",
    "loguru-config==0.1.0",
    "win32-setctime==1.2.0 ; sys_platform == \"win32\"",
]
dev-locked = [
    "certifi==2024.12.14",
    "cfgv==3.4.0",
    "cftime==1.6.4.post1",
    "click==8.1.8",
    "colorama==0.4.6",
    "distlib==0.3.9",
    "filelock==3.16.1",
    "identify==2.6.3",
    "importlib-resources==6.4.5 ; python_version < \"3.10\"",
    "incremental==24.7.2",
    "jinja2==3.1.5",
    "liccheck==0.9.2",
    "loguru==0.7.3",
    "markupsafe==3.0.2",
    "mypy==1.14.0",
    "mypy-extensions==1.0.0",
    "netcdf4==1.7.2",
    "nodeenv==1.9.1",
    "numpy==1.26.4",
    "packaging==24.2",
    "pandas-stubs==2.2.2.240807",
    "pip==24.3.1",
    "platformdirs==4.3.6",
    "pre-commit==4.0.1",
    "pyyaml==6.0.2",
    "semantic-version==2.10.0",
    "setuptools==75.6.0",
    "toml==0.10.2",
    "tomli==2.2.1",
    "towncrier==23.11.0",
    "types-pytz==2024.2.0.20241221",
    "types-requests==2.32.0.20241016",
    "types-tqdm==4.67.0.20241221",
    "typing-extensions==4.12.2",
    "urllib3==2.3.0",
    "virtualenv==20.28.0",
    "win32-setctime==1.2.0 ; sys_platform == \"win32\"",
    "zipp==3.21.0",
]
docs-locked = [
    "alabaster==0.7.16",
    "anyio==4.7.0",
    "appnope==0.1.4 ; platform_system == \"Darwin\"",
    "argon2-cffi==23.1.0",
    "argon2-cffi-bindings==21.2.0",
    "arrow==1.3.0",
    "asttokens==3.0.0",
    "async-lru==2.0.4",
    "attrs==24.3.0",
    "babel==2.16.0",
    "beautifulsoup4==4.12.3",
    "bleach==6.2.0",
    "certifi==2024.12.14",
    "cffi==1.17.1",
    "charset-normalizer==3.4.1",
    "click==8.1.8",
    "colorama==0.4.6",
    "comm==0.2.2",
    "debugpy==1.8.11",
    "decorator==5.1.1",
    "defusedxml==0.7.1",
    "docutils==0.21.2",
    "exceptiongroup==1.2.2 ; python_version < \"3.11\"",
    "executing==2.1.0",
    "fastjsonschema==2.21.1",
    "fqdn==1.5.1",
    "ghp-import==2.1.0",
    "greenlet==3.1.1 ; (platform_machine == \"win32\" or platform_machine == \"WIN32\" or platform_machine == \"AMD64\" or platform_machine == \"amd64\" or platform_machine == \"x86_64\" or platform_machine == \"ppc64le\" or platform_machine == \"aarch64\") and python_version < \"3.13\"",
    "griffe==1.5.1",
    "h11==0.14.0",
    "httpcore==1.0.7",
    "httpx==0.28.1",
    "idna==3.10",
    "imagesize==1.4.1",
    "importlib-metadata==8.5.0",
    "ipykernel==6.29.5",
    "ipython==8.18.1",
    "isoduration==20.11.0",
    "jedi==0.19.2",
    "jinja2==3.1.5",
    "json5==0.10.0",
    "jsonpointer==3.0.0",
    "jsonschema==4.23.0",
    "jsonschema-specifications==2024.10.1",
    "jsonschema[format-nongpl]==4.23.0",
    "jupyter-cache==1.0.1",
    "jupyter-client==8.6.3",
    "jupyter-core==5.7.2",
    "jupyter-events==0.11.0",
    "jupyter-lsp==2.2.5",
    "jupyter-server==2.15.0",
    "jupyter-server-terminals==0.5.3",
    "jupyterlab==4.3.4",
    "jupyterlab-pygments==0.3.0",
    "jupyterlab-server==2.27.3",
    "jupytext==1.16.6",
    "markdown==3.7",
    "markdown-it-py==3.0.0",
    "markupsafe==3.0.2",
    "matplotlib-inline==0.1.7",
    "mdit-py-plugins==0.4.2",
    "mdurl==0.1.2",
    "mergedeep==1.3.4",
    "mistune==3.0.2",
    "mkdocs==1.6.1",
    "mkdocs-autorefs==1.2.0",
    "mkdocs-gen-files==0.5.0",
    "mkdocs-get-deps==0.2.0",
    "mkdocs-jupyter==0.25.1",
    "mkdocs-literate-nav==0.6.1",
    "mkdocs-material==9.5.49",
    "mkdocs-material-extensions==1.3.1",
    "mkdocs-section-index==0.3.9",
    "mkdocstrings==0.27.0",
    "mkdocstrings-python==1.12.2",
    "mkdocstrings[python]==0.27.0",
    "myst-nb==1.1.2",
    "myst-parser==3.0.1",
    "nbclient==0.10.2",
    "nbconvert==7.16.4",
    "nbformat==5.10.4",
    "nest-asyncio==1.6.0",
    "notebook-shim==0.2.4",
    "overrides==7.7.0",
    "packaging==24.2",
    "paginate==0.5.7",
    "pandocfilters==1.5.1",
    "parso==0.8.4",
    "pathspec==0.12.1",
    "pexpect==4.9.0 ; sys_platform != \"win32\"",
    "platformdirs==4.3.6",
    "prometheus-client==0.21.1",
    "prompt-toolkit==3.0.48",
    "psutil==6.1.1",
    "ptyprocess==0.7.0 ; os_name != \"nt\" or sys_platform != \"win32\"",
    "pure-eval==0.2.3",
    "pycparser==2.22",
    "pygments==2.18.0",
    "pymdown-extensions==10.13",
    "python-dateutil==2.9.0.post0",
    "python-json-logger==3.2.1",
    "pywin32==308 ; sys_platform == \"win32\" and platform_python_implementation != \"PyPy\"",
    "pywinpty==2.0.14 ; os_name == \"nt\"",
    "pyyaml==6.0.2",
    "pyyaml-env-tag==0.1",
    "pyzmq==26.2.0",
    "referencing==0.35.1",
    "regex==2024.11.6",
    "requests==2.32.3",
    "rfc3339-validator==0.1.4",
    "rfc3986-validator==0.1.1",
    "rpds-py==0.22.3",
    "send2trash==1.8.3",
    "setuptools==75.6.0",
    "six==1.17.0",
    "sniffio==1.3.1",
    "snowballstemmer==2.2.0",
    "soupsieve==2.6",
    "sphinx==7.4.7",
    "sphinxcontrib-applehelp==2.0.0",
    "sphinxcontrib-devhelp==2.0.0",
    "sphinxcontrib-htmlhelp==2.1.0",
    "sphinxcontrib-jsmath==1.0.1",
    "sphinxcontrib-qthelp==2.0.0",
    "sphinxcontrib-serializinghtml==2.0.0",
    "sqlalchemy==2.0.36",
    "stack-data==0.6.3",
    "tabulate==0.9.0",
    "terminado==0.18.1",
    "tinycss2==1.4.0",
    "tomli==2.2.1",
    "tornado==6.4.2",
    "traitlets==5.14.3",
    "types-python-dateutil==2.9.0.20241206",
    "typing-extensions==4.12.2",
    "uri-template==1.3.0",
    "urllib3==2.3.0",
    "watchdog==6.0.0",
    "wcwidth==0.2.13",
    "webcolors==24.11.1",
    "webencodings==0.5.1",
    "websocket-client==1.8.0",
    "zipp==3.21.0",
]
notebooks-locked = [
    "anyio==4.7.0",
    "appnope==0.1.4 ; platform_system == \"Darwin\"",
    "argon2-cffi==23.1.0",
    "argon2-cffi-bindings==21.2.0",
    "arrow==1.3.0",
    "asttokens==3.0.0",
    "async-lru==2.0.4",
    "attrs==24.3.0",
    "babel==2.16.0",
    "beautifulsoup4==4.12.3",
    "bleach==6.2.0",
    "certifi==2024.12.14",
    "cffi==1.17.1",
    "charset-normalizer==3.4.1",
    "colorama==0.4.6",
    "comm==0.2.2",
    "debugpy==1.8.11",
    "decorator==5.1.1",
    "defusedxml==0.7.1",
    "exceptiongroup==1.2.2 ; python_version < \"3.11\"",
    "executing==2.1.0",
    "fastjsonschema==2.21.1",
    "fqdn==1.5.1",
    "h11==0.14.0",
    "httpcore==1.0.7",
    "httpx==0.28.1",
    "idna==3.10",
    "importlib-metadata==8.5.0",
    "ipykernel==6.29.5",
    "ipython==8.18.1",
    "isoduration==20.11.0",
    "jedi==0.19.2",
    "jinja2==3.1.5",
    "json5==0.10.0",
    "jsonpointer==3.0.0",
    "jsonschema==4.23.0",
    "jsonschema-specifications==2024.10.1",
    "jsonschema[format-nongpl]==4.23.0",
    "jupyter-client==8.6.3",
    "jupyter-core==5.7.2",
    "jupyter-events==0.11.0",
    "jupyter-lsp==2.2.5",
    "jupyter-server==2.15.0",
    "jupyter-server-terminals==0.5.3",
    "jupyterlab==4.3.4",
    "jupyterlab-pygments==0.3.0",
    "jupyterlab-server==2.27.3",
    "jupytext==1.16.6",
    "markdown-it-py==3.0.0",
    "markupsafe==3.0.2",
    "matplotlib-inline==0.1.7",
    "mdit-py-plugins==0.4.2",
    "mdurl==0.1.2",
    "mistune==3.0.2",
    "nbclient==0.10.2",
    "nbconvert==7.16.4",
    "nbformat==5.10.4",
    "nest-asyncio==1.6.0",
    "notebook-shim==0.2.4",
    "overrides==7.7.0",
    "packaging==24.2",
    "pandocfilters==1.5.1",
    "parso==0.8.4",
    "pexpect==4.9.0 ; sys_platform != \"win32\"",
    "platformdirs==4.3.6",
    "prometheus-client==0.21.1",
    "prompt-toolkit==3.0.48",
    "psutil==6.1.1",
    "ptyprocess==0.7.0 ; os_name != \"nt\" or sys_platform != \"win32\"",
    "pure-eval==0.2.3",
    "pycparser==2.22",
    "pygments==2.18.0",
    "python-dateutil==2.9.0.post0",
    "python-json-logger==3.2.1",
    "pywin32==308 ; sys_platform == \"win32\" and platform_python_implementation != \"PyPy\"",
    "pywinpty==2.0.14 ; os_name == \"nt\"",
    "pyyaml==6.0.2",
    "pyzmq==26.2.0",
    "referencing==0.35.1",
    "requests==2.32.3",
    "rfc3339-validator==0.1.4",
    "rfc3986-validator==0.1.1",
    "rpds-py==0.22.3",
    "send2trash==1.8.3",
    "setuptools==75.6.0",
    "six==1.17.0",
    "sniffio==1.3.1",
    "soupsieve==2.6",
    "stack-data==0.6.3",
    "terminado==0.18.1",
    "tinycss2==1.4.0",
    "tomli==2.2.1",
    "tornado==6.4.2",
    "traitlets==5.14.3",
    "types-python-dateutil==2.9.0.20241206",
    "typing-extensions==4.12.2",
    "uri-template==1.3.0",
    "urllib3==2.3.0",
    "wcwidth==0.2.13",
    "webcolors==24.11.1",
    "webencodings==0.5.1",
    "websocket-client==1.8.0",
    "zipp==3.21.0",
]
tests-locked = [
    "colorama==0.4.6",
    "coverage==7.6.9",
    "coverage[toml]==7.6.9",
    "exceptiongroup==1.2.2 ; python_version < \"3.11\"",
    "iniconfig==2.0.0",
    "packaging==24.2",
    "pluggy==1.5.0",
    "pytest==8.3.4",
    "pytest-cov==6.0.0",
    "pytest-datadir==1.5.0",
    "pytest-regressions==2.6.0",
    "pyyaml==6.0.2",
    "tomli==2.2.1",
]

[project.scripts]
input4mips-validation = "input4mips_validation.cli:app"

[tool.pixi.feature.py39.dependencies]
python = "3.9.*"

[tool.pixi.feature.py310.dependencies]
python = "3.10.*"

[tool.pixi.feature.py311.dependencies]
python = "3.11.*"

[tool.pixi.environments.default]
features = [
    "py39",
]

[tool.pixi.environments.docs]
features = [
    "docs",
]
solve-group = "default"

[tool.pixi.environments.all-dev]
features = [
    "loguru-config",
    "dev",
    "docs",
    "notebooks",
    "tests",
]
solve-group = "default"

[tool.pixi.environments.py39]
features = [
    "py39",
]
solve-group = "default"

[tool.pixi.environments.py310]
features = [
    "py310",
]

[tool.pixi.environments.py311]
features = [
    "py311",
]

[tool.pixi.environments.test-py39]
features = [
    "tests",
]
solve-group = "default"

[tool.pixi.environments.test-py310]
features = [
    "tests",
    "py310",
]

[tool.pixi.environments.test-py311]
features = [
    "tests",
    "py311",
]

[tool.pixi.project]
channels = [
    "conda-forge",
]
platforms = [
    "osx-64",
    "osx-arm64",
    "linux-64",
    "linux-aarch64",
    "win-64",
]

[tool.pixi.pypi-dependencies.input4mips_validation]
path = "."
editable = true

[tool.pixi.tasks]

[tool.pixi.dependencies]
cfchecker = ">=4.1.0"
cftime = ">=1.0"
iris = ">=3.0"
netcdf4 = ">=1.0"
numpy = "<2.0"

[tool.pdm.build]
locked = true
includes = [
    "src/input4mips_validation",
    "LICENCE",
]

[tool.coverage.run]
source = [
    "src",
]
branch = true

[tool.coverage.report]
fail_under = 70
skip_empty = true
show_missing = true
exclude_also = [
    "if TYPE_CHECKING",
]

[tool.mypy]
strict = true
disallow_any_unimported = true
show_error_codes = true
show_error_context = true
warn_unreachable = true
follow_imports = "normal"

[tool.jupytext]
formats = "ipynb,py:percent"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.ruff]
src = [
    "src",
]
target-version = "py39"
line-length = 88

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "D",
    "PL",
    "TRY",
    "NPY",
    "RUF",
    "UP",
    "S",
]
unfixable = [
    "PD002",
]
ignore = [
    "D200",
    "D400",
    "UP007",
]

[tool.ruff.lint.per-file-ignores]
"test*.py" = [
    "D",
    "S101",
    "PLR2004",
]
"docs/*" = [
    "D100",
    "E402",
    "S101",
]
"scripts/*" = [
    "S101",
]
"stubs/*" = [
    "PLR0913",
]

[tool.ruff.lint.isort]
known-first-party = [
    "src",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
docstring-code-format = true

[tool.towncrier]
package = "input4mips_validation"
package_dir = "src"
filename = "docs/changelog.md"
directory = "changelog/"
title_format = "## Input4MIPs validation {version} ({project_date})"
underlines = [
    "",
    "",
    "",
]
issue_format = "[#{issue}](https://github.com/climate-resource/input4mips_validation/pull/{issue})"
type = [
    { directory = "breaking", name = "âš ï¸ Breaking Changes", showcontent = true },
    { directory = "deprecation", name = "ðŸ—‘ï¸ Deprecations", showcontent = true },
    { directory = "feature", name = "ðŸ†• Features", showcontent = true },
    { directory = "improvement", name = "ðŸŽ‰ Improvements", showcontent = true },
    { directory = "fix", name = "ðŸ› Bug Fixes", showcontent = true },
    { directory = "docs", name = "ðŸ“š Improved Documentation", showcontent = true },
    { directory = "trivial", name = "ðŸ”§ Trivial/Internal Changes", showcontent = false },
]

[tool.liccheck]
authorized_licenses = [
    "bsd",
    "bsd license",
    "BSD 3-Clause",
    "CC0",
    "apache",
    "apache 2.0",
    "apache software",
    "apache software license",
    "Apache License, Version 2.0",
    "Historical Permission Notice and Disclaimer (HPND)",
    "isc license",
    "isc license (iscl)",
    "gnu lgpl",
    "lgpl with exceptions or zpl",
    "LGPLv2+",
    "GNU Lesser General Public License v2 (LGPLv2)",
    "GNU Lesser General Public License v2 or later (LGPLv2+)",
    "mit",
    "mit license",
    "Mozilla Public License 2.0 (MPL 2.0)",
    "python software foundation",
    "python software foundation license",
    "zpl 2.1",
]
unauthorized_licenses = [
    "agpl",
    "gnu agpl",
    "gpl v3",
    "gplv3",
    "gpl v2",
    "gplv2",
    "gpl v1",
    "gplv1",
]

[build-system]
requires = [
    "pdm-backend",
    "pdm-build-locked",
]
build-backend = "pdm.backend"
