[project]
name = "ukbeaver"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.2",
    "polars>=1.33.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "notebook>=7.4.7",
]
