[project]
name = "linux-api"
version = "2.0.0"
description = "A linux API server to get system informations and other live informations about your linux machine."
authors = [{ name = "Ivole32", email = "ivo.theis@posteo.de" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.118.0",
    "uvicorn==0.37.0",
    "slowapi==0.1.9",
    "pydantic==2.11.9",
    "bcrypt==5.0.0",
    "psutil==7.1.0",
    "python-dotenv==1.1.1"
]

[project.scripts]
linux-api = "linux_api.start:main"

[tool.setuptools]
packages = ["linux_api"]

include-package-data = true