[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "horizen-fastapi-template"
version = "0.1.1"
description = """A reusable FastAPI application factory
The main contributor and maintainer is Chaim Mendelson, with contributions from Yehonatan Magen."""
readme = "README.md"
authors = [{ name = "Chaim Mendelson and Yehonatan Magen" }]
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = [
    "aioftp>=0.21",
    "fastapi>=0.110",
    "httpx>=0.24",
    "kubernetes-asyncio>=29.0",
    "loguru>=0.7",
    "prometheus-client>=0.17",
    "pydantic>=2.0",
    "pydantic-settings>=2.0",
]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
fastapi_template = ["static/**"]

[tool.setuptools]
include-package-data = true