[project]
name = "pyahmia"
version = "0.1.1"
description = "Search hidden services on the Tor network."
authors = [
    { name = "Escrapism", email = "escrapism@duck.com" }
]
license = "MIT"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Intended Audience :: End Users/Desktop",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English"
]

[tool.poetry.urls]
issues = "https://github.com/escrapism/pyahmia/issues"
repository = "https://github.com/escrapism/pyahmia"

[tool.poetry.dependencies]
python = "^3.11"
requests-tor = "^1.4"
BeautifulSoup4 = "^4.13.4"
rich-click = "^1.8.9"

[tool.poetry.scripts]
ahmia = "pyahmia._cli:cli"
pyahmia = "pyahmia._cli:cli"

[build-system]
requires = ["poetry-core>=2.2.1,<3.0.0"]
build-backend = "poetry.core.masonry.api"
